[2019-02-17 21:58:46,896] 48721_worker_server INFO:Socket starts at 127.0.0.1:48721
[2019-02-17 21:58:46,897] 48721_worker_server INFO:Listening...
[2019-02-17 21:58:51,184] 48721_worker_server INFO:Listening...
[2019-02-17 21:58:51,185] Client_Thread-1 INFO:Got connection from 127.0.0.1:34524
[2019-02-17 21:58:51,185] Client_Thread-1 INFO:The connection's group name is admin
[2019-02-17 21:58:51,185] Client_Thread-1 INFO:Recieving the Python script file...
[2019-02-17 21:58:51,231] Client_Thread-1 INFO:Writing the Python script file to /home/zhiangz/Documents/48721_ass3_part1/rmt_worker/log/admin/Eplus-env-run41...
[2019-02-17 21:58:51,231] Client_Thread-1 INFO:Writing is finished
[2019-02-17 21:58:51,232] Client_Thread-1 INFO:Starting to run the script
[2019-02-17 21:58:51,233] Client_Thread-1 INFO:Finished task for 127.0.0.1:34524
[2019-02-17 21:58:51,234] Client_Thread-1 INFO:/bin/sh: 1: Syntax error: "&" unexpected

[2019-02-17 21:58:51,234] Client_Thread-1 INFO:Zipping the results...
[2019-02-17 21:58:51,237] Client_Thread-1 INFO:Zipping is successful
[2019-02-17 21:58:51,238] Client_Thread-1 ERROR:Error is encountered when zipping the results, Traceback (most recent call last):
  File "/home/zhiangz/Documents/48721_ass3_part1/rmt_worker/server.py", line 135, in _python_process_handler
    s.sendall(f_line);
NameError: name 's' is not defined

