[2019-02-17 21:59:13,420] 48721_worker_server INFO:Socket starts at 127.0.0.1:48721
[2019-02-17 21:59:13,421] 48721_worker_server INFO:Listening...
[2019-02-17 21:59:15,394] 48721_worker_server INFO:Listening...
[2019-02-17 21:59:15,394] Client_Thread-1 INFO:Got connection from 127.0.0.1:34526
[2019-02-17 21:59:15,395] Client_Thread-1 INFO:The connection's group name is admin
[2019-02-17 21:59:15,395] Client_Thread-1 INFO:Recieving the Python script file...
[2019-02-17 21:59:15,438] Client_Thread-1 INFO:Writing the Python script file to /home/zhiangz/Documents/48721_ass3_part1/rmt_worker/log/admin/Eplus-env-run42...
[2019-02-17 21:59:15,438] Client_Thread-1 INFO:Writing is finished
[2019-02-17 21:59:15,439] Client_Thread-1 INFO:Starting to run the script
[2019-02-17 21:59:15,441] Client_Thread-1 INFO:Finished task for 127.0.0.1:34526
[2019-02-17 21:59:15,441] Client_Thread-1 INFO:/bin/sh: 1: Syntax error: "&" unexpected

[2019-02-17 21:59:15,442] Client_Thread-1 INFO:Zipping the results...
[2019-02-17 21:59:15,446] Client_Thread-1 INFO:Zipping is successful
[2019-02-17 21:59:15,447] Client_Thread-1 ERROR:Error is encountered when zipping the results, Traceback (most recent call last):
  File "/home/zhiangz/Documents/48721_ass3_part1/rmt_worker/server.py", line 139, in _python_process_handler
    os.remove(this_gp_dir + 'results.zip')
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhiangz/Documents/48721_ass3_part1/rmt_worker/log/adminresults.zip'

