[2019-02-17 21:55:43,654] 48721_worker_server INFO:Socket starts at 127.0.0.1:48721
[2019-02-17 21:55:43,654] 48721_worker_server INFO:Listening...
[2019-02-17 21:55:48,196] 48721_worker_server INFO:Listening...
[2019-02-17 21:55:48,196] Client_Thread-1 INFO:Got connection from 127.0.0.1:34506
[2019-02-17 21:55:48,196] Client_Thread-1 INFO:The connection's group name is admin
[2019-02-17 21:55:48,196] Client_Thread-1 INFO:Recieving the Python script file...
[2019-02-17 21:55:48,244] Client_Thread-1 INFO:Writing the Python script file to /home/zhiangz/Documents/48721_ass3_part1/rmt_worker/log/admin/Eplus-env-run40...
[2019-02-17 21:55:48,244] Client_Thread-1 INFO:Writing is finished
[2019-02-17 21:55:48,244] Client_Thread-1 INFO:Starting to run the script
[2019-02-17 21:55:48,247] Client_Thread-1 INFO:Finished task for 127.0.0.1:34506
[2019-02-17 21:55:48,799] Client_Thread-1 INFO:2019-02-17 21:55:48,798-xremote-INFO-2323220

[2019-02-17 21:55:49,300] Client_Thread-1 INFO:2019-02-17 21:55:49,300-xremote-INFO-2323221

[2019-02-17 21:55:49,801] Client_Thread-1 INFO:2019-02-17 21:55:49,801-xremote-INFO-2323222

[2019-02-17 21:55:50,304] Client_Thread-1 INFO:2019-02-17 21:55:50,304-xremote-INFO-2323223

[2019-02-17 21:55:50,806] Client_Thread-1 INFO:2019-02-17 21:55:50,806-xremote-INFO-2323224

[2019-02-17 21:55:51,308] Client_Thread-1 INFO:2019-02-17 21:55:51,307-xremote-INFO-2323225

[2019-02-17 21:55:51,809] Client_Thread-1 INFO:2019-02-17 21:55:51,809-xremote-INFO-2323226

[2019-02-17 21:55:52,312] Client_Thread-1 INFO:2019-02-17 21:55:52,311-xremote-INFO-2323227

[2019-02-17 21:55:52,813] Client_Thread-1 INFO:2019-02-17 21:55:52,813-xremote-INFO-2323228

[2019-02-17 21:55:53,320] Client_Thread-1 INFO:2019-02-17 21:55:53,314-xremote-INFO-2323229

[2019-02-17 21:55:53,320] Client_Thread-1 INFO:Zipping the results...
[2019-02-17 21:55:53,323] Client_Thread-1 INFO:Zipping is successful
[2019-02-17 21:55:53,324] Client_Thread-1 ERROR:Error is encountered when zipping the results, Traceback (most recent call last):
  File "/home/zhiangz/Documents/48721_ass3_part1/rmt_worker/server.py", line 128, in _python_process_handler
    res_size = os.path.getsize(run_dir + '/results.zip');
  File "/home/zhiangz/Documents/48721_ass3_part1/virt_env/lib/python3.5/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/zhiangz/Documents/48721_ass3_part1/rmt_worker/log/admin/Eplus-env-run40/results.zip'

